### PR TITLE
Use promises + Capacitor 3

### PR DESCRIPTION
**Pull request by JumBay**
- Use promises instead of callback 
- Change action event name `music-controls-skip-to` to `music-controls-seek-to` to keep the same event name as the cordova mucisc controls plugin

### CODE REVIEW

**Comment by ingageco** [comment]
Thank you - looks like a good PR. The action event name was changed intentionally to introduce the ability to do a +30sec jump or -30sec jump like you see in many podcast apps. Can the PR re-introduce the skip functions in addition to seek instead of revise it?

**Comment by JumBay** [comment]
Ok if it was intentionally then I went back to `music-controls-skip-to`. I did the change because it was still `music-controls-seek-to` in the README. 
I prefer we keep only one event name and add a warning in the doc for this.

**Comment by ingageco** [comment]
@JumBay by adding Capacitor 3 support, does this also continue to support Capacitor 2?

**Comment by JumBay** [comment]
Sorry I cannot tell, I don't have any project running capacitor v2 anymore.

**Comment by yocontra** [comment]
@ingageco Anything I can do to help get this merged? Additional testing needed?

**Comment by yocontra** [comment]
@JumBay FYI been doing some testing and I'm not able to get your updated version to work on iOS - the current version before your changes also doesn't work on iOS either based on looking through the issues filed.

**Comment by JumBay** [comment]
Do you test on a real device or on simulator? On simulator it almost never works. Also are you playing a song?

**Comment by yocontra** [comment]
@JumBay On a real device - the simulator doesn't implement lock screen media controls AFAIK. Yep playing a song using the WebAudio API. Without using this plugin we have working play/pause on the lock screen just using the standard browser APIs - when using this plugin to try to provide more metadata (album art, artist, etc.) we lose all of the controls and don't even get the native browser controls anymore.

**Comment by JumBay** [comment]
@contra I use this plugin in special way, it's being used as a remote control. I play a "fake" song using this cordova plugin https://github.com/wako-app/cordova-plugin-media.git

**Comment by ingageco** [comment]
@JumBay I released a new repo / version of this plugin with all of your edits, and explicit credit. It's available on npmjs as well. Link: https://github.com/ingageco/capacitor-music-controls-plugin-v3

I didn't merge in this repo so a version supporting v2 can remain available.

**Pull request closed without merging**
